Logo v2 website
ethgdl/website pull request #7
Opened 2020-07-31 20:21 UTC by daniniguez

2020-08-09 16:37 UTC, hugo-dc commented
Hay que eliminar las imagenes que ya no se necesitan: `ethgdl-logo.png` y  `logo64x64.png`

2020-08-12 01:23 UTC, daniniguez commented
Logos v1 eliminadas.

2020-08-13 06:41 UTC, hugo-dc requested changes
El logo de 64x64 se apreciaría mejor sin letras

2020-08-13 23:24 UTC, daniniguez commented
Logo de 64px modificado: letras eliminadas.

2020-08-14 06:58 UTC, hugo-dc requested changes
El nombre del archivo de 64px debe ser `eth-gdl-website-64.png`

2020-08-14 20:43 UTC, daniniguez commented
Archivo renombrado.

2020-08-15 22:27 UTC, hugo-dc approved these changes
:+1:

2020-08-15 22:27 UTC, merged